app:
  image: wifigo
  ports:
    - "87:3000"
    
  links:
    - mongo
  environment:
    - ROOT_URL=http://localhost
    - MONGO_URL=mongodb://mongo:27017/meteor
    - 'METEOR_SETTINGS={ 
        "DBSQLSERVER_HOST":"10.8.3.29",
        "DBSQLSERVER_PORT":"57055", 
        "DBSQLSERVER_USER":"reportvie",
        "DBSQLSERVER_PASSWORD":"reportvie",
        "DBSQLSERVER_DATABASE":"SUNDB_RCI",
        "DBSQLSERVER_BCIVIE_HOST":"10.10.3.40",
        "DBSQLSERVER_BCIVIE_PORT":"56778",
        "DBSQLSERVER_BCIVIE_USER":"sa",
        "DBSQLSERVER_BCIVIE_PASSWORD":"Nsi@Vie2013",
        "DBSQLSERVER_BCIVIE_DATABASE":"B_CIVIE","ADMINMAIL":"thibaut.zehi@groupensia.com"}'
  restart: always
mongo:
  image: mongo:latest 
  restart: always